from pathlib import Path


def write(path: str, lines: list[str]) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


docs = {
    "docs/parts/part_a_raw_graphs.md": [
        "# Part A — Raw graph ingestion",
        "",
        "Part A prepares the raw graph datasets used throughout the GCO-HPIF pipeline.",
        "",
        "## Purpose",
        "",
        "This stage downloads or reads the source graph datasets, normalizes them into a common internal representation, and writes graph manifests that later stages can consume.",
        "",
        "## Datasets",
        "",
        "- `TWITTER`",
        "- `COLLAB`",
        "- `IMDB-BINARY`",
        "",
        "## Smoke test",
        "",
        "```bash",
        "python -m gco_hpif.cli.prepare_raw_graphs \\",
        "  --output-root artifacts/slice_a_smoke \\",
        "  --datasets imdb_binary collab twitter \\",
        "  --limit 3",
        "```",
        "",
        "## Full run",
        "",
        "```bash",
        "python -m gco_hpif.cli.prepare_raw_graphs \\",
        "  --output-root artifacts/slice_a_full \\",
        "  --datasets imdb_binary collab twitter",
        "```",
        "",
        "## Main outputs",
        "",
        "```text",
        "artifacts/slice_a_full/",
        "├── raw/",
        "├── interim/",
        "│   ├── twitter_graphs.pkl.gz",
        "│   ├── collab_graphs.pkl.gz",
        "│   └── imdb_binary_graphs.pkl.gz",
        "└── manifests/",
        "    ├── graphs_index.csv",
        "    └── dataset_summary.csv",
        "```",
        "",
        "## Notes",
        "",
        "- Generated artifacts should not be committed to Git.",
        "- Later stages use the manifest files and serialized graph objects written by this part.",
    ],
    "docs/parts/part_b_twitter_split.md": [
        "# Part B — TWITTER split manifest",
        "",
        "Part B creates the fixed TWITTER train/validation/test split used by trainable solver integrations.",
        "",
        "## Purpose",
        "",
        "The goal is to make all trainable experiments reproducible by using a fixed split rather than regenerating random partitions.",
        "",
        "## Command",
        "",
        "```bash",
        "python -m gco_hpif.cli.make_twitter_split \\",
        "  --graphs-index artifacts/slice_a_full/manifests/graphs_index.csv \\",
        "  --output data/manifests/twitter_split_60_20_20.csv",
        "```",
        "",
        "## Expected split counts",
        "",
        "| Split | Count |",
        "|---|---:|",
        "| train | 584 |",
        "| validation | 195 |",
        "| test | 194 |",
        "",
        "## Main output",
        "",
        "```text",
        "data/manifests/twitter_split_60_20_20.csv",
        "```",
        "",
        "## Notes",
        "",
        "This split manifest should be committed because it defines the reproducible TWITTER split used by downstream stages.",
    ],
    "docs/parts/part_c_features.md": [
        "# Part C — NetworkX graph features",
        "",
        "Part C computes graph-level NetworkX features for every graph instance.",
        "",
        "## Purpose",
        "",
        "These features are the main explanatory and predictive variables used in the hardness-classification and runtime-prediction stages.",
        "",
        "## Smoke test",
        "",
        "```bash",
        "python -m gco_hpif.cli.compute_graph_features \\",
        "  --graphs-index artifacts/slice_a_smoke/manifests/graphs_index.csv \\",
        "  --interim-dir artifacts/slice_a_smoke/interim \\",
        "  --output-dir artifacts/features_smoke \\",
        "  --datasets twitter collab imdb_binary \\",
        "  --limit-per-dataset 3 \\",
        "  --timeout-seconds 60",
        "```",
        "",
        "## Full run",
        "",
        "```bash",
        "python -m gco_hpif.cli.compute_graph_features \\",
        "  --graphs-index artifacts/slice_a_full/manifests/graphs_index.csv \\",
        "  --interim-dir artifacts/slice_a_full/interim \\",
        "  --output-dir artifacts/features_full \\",
        "  --datasets twitter collab imdb_binary \\",
        "  --timeout-seconds 60",
        "```",
        "",
        "## Main outputs",
        "",
        "```text",
        "artifacts/features_full/",
        "├── graph_features.csv",
        "├── feature_failures.csv",
        "├── feature_timing_summary.csv",
        "└── feature_column_manifest.csv",
        "```",
        "",
        "## Predictor-column rule",
        "",
        "Only columns beginning with `feature_` should be treated as graph-feature predictors in later ML stages.",
    ],
    "docs/parts/part_d_solvers.md": [
        "# Part D — Solver wrappers",
        "",
        "Part D contains wrappers for Maximum Clique Problem solver runs.",
        "",
        "## Solver integrations",
        "",
        "| Part | Solver | Notes |",
        "|---|---|---|",
        "| D.1 | Gurobi | Requires `gurobipy` and a valid Gurobi license |",
        "| D.2 | CliSAT | Requires CliSAT executable or build |",
        "| D.3 | MoMC | Requires MoMC source or executable |",
        "| D.4 | EGN | Optional learned solver integration |",
        "| D.5 | HGS | Optional heuristic/learned integration |",
        "",
        "## Purpose",
        "",
        "Each solver wrapper should run a solver on graph instances and produce standardized output that can be joined in Part E.",
        "",
        "## Common output contract",
        "",
        "Each solver output directory should contain a standardized file:",
        "",
        "```text",
        "solver_runs.csv",
        "```",
        "",
        "Typical output directories include:",
        "",
        "```text",
        "artifacts/solver_runs/gurobi_full/",
        "artifacts/solver_runs/clisat_full/",
        "artifacts/solver_runs/momc_full/",
        "artifacts/solver_runs/egn_full_all_test_graphs_fixed/",
        "artifacts/solver_runs/hgs_full_all_test_graphs/",
        "```",
        "",
        "## Notes",
        "",
        "- Gurobi requires a license.",
        "- EGN and HGS may require external repositories and environment-specific setup.",
        "- Part E expects all solver outputs to use a consistent `solver_runs.csv` structure.",
    ],
    "docs/parts/part_e_hardness_labels.md": [
        "# Part E — Runtime-consensus hardness labels",
        "",
        "Part E constructs empirical hardness labels using solver runtimes.",
        "",
        "## Required solver outputs",
        "",
        "```text",
        "artifacts/solver_runs/gurobi_full/solver_runs.csv",
        "artifacts/solver_runs/clisat_full/solver_runs.csv",
        "artifacts/solver_runs/momc_full/solver_runs.csv",
        "artifacts/solver_runs/egn_full_all_test_graphs_fixed/solver_runs.csv",
        "artifacts/solver_runs/hgs_full_all_test_graphs/solver_runs.csv",
        "```",
        "",
        "Use the fixed EGN file:",
        "",
        "```text",
        "artifacts/solver_runs/egn_full_all_test_graphs_fixed/solver_runs.csv",
        "```",
        "",
        "## Common five-solver instance set",
        "",
        "```text",
        "6194 instances total",
        "5000 COLLAB",
        "1000 IMDB-BINARY",
        "194 TWITTER",
        "```",
        "",
        "## Labels",
        "",
        "Primary label:",
        "",
        "```text",
        "consensus5_runtime_hardness_label_binary",
        "```",
        "",
        "Sensitivity labels:",
        "",
        "```text",
        "consensus4_runtime_hardness_label_binary",
        "majority3_runtime_hardness_label_binary",
        "```",
        "",
        "## Definition",
        "",
        "An instance is labelled `Hard` under the consensus-5 label if it is in the top runtime quartile for all five solvers, with the top runtime quartile computed separately by dataset and solver.",
        "",
        "## Main output",
        "",
        "```text",
        "artifacts/hardness_labels_consensus_runtime/hardness_labels.csv",
        "```",
    ],
    "docs/parts/part_f_hardness_classification.md": [
        "# Part F — ML hardness classification",
        "",
        "Part F trains graph-feature-based classifiers to predict runtime-consensus hardness labels.",
        "",
        "## Inputs",
        "",
        "```text",
        "artifacts/features_full/graph_features.csv",
        "artifacts/hardness_labels_consensus_runtime/hardness_labels.csv",
        "```",
        "",
        "## Join keys",
        "",
        "```text",
        "dataset",
        "graph_id",
        "source_index",
        "```",
        "",
        "## Predictor rule",
        "",
        "Only columns beginning with `feature_` are valid predictors.",
        "",
        "Do not use solver runtimes, top-runtime flags, label columns, best clique sizes, or other solver-derived columns as graph-feature predictors.",
        "",
        "## Models",
        "",
        "- Random Forest",
        "- Logistic Regression",
        "- SVC",
        "- XGBoost, if installed",
        "",
        "## Feature selection",
        "",
        "Feature selection uses ANOVA `SelectKBest` and selects the first peak or early plateau of minority-class F1.",
        "",
        "## Main output directory",
        "",
        "```text",
        "artifacts/ml_hardness_part_f_feature_prefix_fixed/",
        "```",
        "",
        "## Important selected-feature files",
        "",
        "```text",
        "artifacts/ml_hardness_part_f_feature_prefix_fixed/consensus5_runtime_hardness_label_binary/tables/selected_features_anova_first_peak.csv",
        "artifacts/ml_hardness_part_f_feature_prefix_fixed/consensus4_runtime_hardness_label_binary/tables/selected_features_anova_first_peak.csv",
        "artifacts/ml_hardness_part_f_feature_prefix_fixed/majority3_runtime_hardness_label_binary/tables/selected_features_anova_first_peak.csv",
        "```",
    ],
    "docs/parts/part_g_association_rules.md": [
        "# Part G — Association-rule mining",
        "",
        "Part G mines FP-Growth association rules for hardness interpretation.",
        "",
        "## Design choice",
        "",
        "Do not mine over all 23 graph features. Use only the target-specific Part F first-peak selected features.",
        "",
        "This keeps the rule-mining problem smaller and the resulting rules more interpretable.",
        "",
        "## Targets",
        "",
        "```text",
        "consensus5_runtime_hardness_label_binary",
        "consensus4_runtime_hardness_label_binary",
        "majority3_runtime_hardness_label_binary",
        "```",
        "",
        "## Feature bins",
        "",
        "```text",
        "3 bins: 0–33, 33–66, 66–100",
        "4 bins: 0–25, 25–50, 50–75, 75–100",
        "5 bins: 0–20, 20–40, 40–60, 60–80, 80–100",
        "```",
        "",
        "## Consequents",
        "",
        "Consequents are restricted to standalone labels:",
        "",
        "```text",
        "Hard",
        "Not Hard",
        "```",
        "",
        "## Main command",
        "",
        "```bash",
        "PYTHONPATH=$PWD/src python -m gco_hpif.cli.mine_hardness_rules \\",
        "  --features artifacts/features_full/graph_features.csv \\",
        "  --labels artifacts/hardness_labels_consensus_runtime/hardness_labels.csv \\",
        "  --part-f-output-dir artifacts/ml_hardness_part_f_feature_prefix_fixed \\",
        "  --output-dir artifacts/association_rules_part_g \\",
        "  --bin-counts 3 4 5 \\",
        "  --min-support auto \\",
        "  --min-confidence 0.60 \\",
        "  --min-lift 1.0 \\",
        "  --max-rule-antecedents 3 \\",
        "  --max-rules-per-group 25 \\",
        "  --min-matched-rows 10 \\",
        "  --max-selected-features-per-target 10 \\",
        "  --evaluation-scope all",
        "```",
        "",
        "## Main outputs",
        "",
        "```text",
        "artifacts/association_rules_part_g/",
        "├── selected_association_rules_part_g.csv",
        "├── association_rule_runtime_summary_part_g.csv",
        "├── model_selection_by_dataset_part_g.csv",
        "└── part_g_association_rules.xlsx",
        "```",
    ],
    "docs/parts/part_h_runtime_prediction.md": [
        "# Part H — Runtime prediction",
        "",
        "Part H predicts solver runtime from graph features.",
        "",
        "## Inputs",
        "",
        "```text",
        "artifacts/features_full/graph_features.csv",
        "artifacts/solver_runs/gurobi_full/solver_runs.csv",
        "artifacts/solver_runs/clisat_full/solver_runs.csv",
        "artifacts/solver_runs/momc_full/solver_runs.csv",
        "artifacts/solver_runs/egn_full_all_test_graphs_fixed/solver_runs.csv",
        "artifacts/solver_runs/hgs_full_all_test_graphs/solver_runs.csv",
        "```",
        "",
        "## Predictors",
        "",
        "Use valid `feature_` columns from Part C.",
        "",
        "## Target",
        "",
        "```text",
        "log(runtime_seconds)",
        "```",
        "",
        "Runtime spans orders of magnitude, so the model learns log-runtime and transforms predictions back to seconds for evaluation.",
        "",
        "## Models",
        "",
        "- XGBoost Regressor",
        "- Random Forest Regressor",
        "- Support Vector Regressor",
        "- Linear/Ridge Regression baseline",
        "",
        "For runtime prediction, the correct support-vector model is `SVR`, not `SVC`.",
        "",
        "## Full command",
        "",
        "```bash",
        "PYTHONPATH=$PWD/src python -m gco_hpif.cli.train_runtime_predictors \\",
        "  --features artifacts/features_full/graph_features.csv \\",
        "  --solver-runs \\",
        "    artifacts/solver_runs/gurobi_full/solver_runs.csv \\",
        "    artifacts/solver_runs/clisat_full/solver_runs.csv \\",
        "    artifacts/solver_runs/momc_full/solver_runs.csv \\",
        "    artifacts/solver_runs/egn_full_all_test_graphs_fixed/solver_runs.csv \\",
        "    artifacts/solver_runs/hgs_full_all_test_graphs/solver_runs.csv \\",
        "  --output-dir artifacts/runtime_prediction_part_h \\",
        "  --models XGB,RF,SVR,LR \\",
        "  --grid-size compact \\",
        "  --cv-folds 5 \\",
        "  --test-size 0.20 \\",
        "  --grid-n-jobs 1 \\",
        "  --model-n-jobs 1",
        "```",
        "",
        "## Main outputs",
        "",
        "```text",
        "artifacts/runtime_prediction_part_h/",
        "├── runtime_prediction_part_h_config.json",
        "├── part_h_runtime_prediction_results.xlsx",
        "├── tables/",
        "├── plots/",
        "└── models/",
        "```",
    ],
}

for path, lines in docs.items():
    write(path, lines)

print("Populated Part A-H docs with concise content.")
